export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SUCCESS_ADD_PRODUCT = 'SUCCESS_ADD_PRODUCT';
export const FAILURE_ADD_PRODUCT = 'FAILURE_ADD_PRODUCT';


export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';


export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';