export const FORM_VALIDATE = 'FORM_VALIDATE';
export const SUCCESS_FORM_VALIDATE = 'SUCCESS_FORM_VALIDATE';
export const FAILURE_FORM_VALIDATE = 'FAILURE_FORM_VALIDATE'; 

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SUCCESS_ADD_PRODUCT = 'SUCCESS_ADD_PRODUCT';
export const FAILURE_ADD_PRODUCT = 'FAILURE_ADD_PRODUCT';